- name: Install HDP requirements
  hosts: hdp
  become: yes
  become_method: sudo
  tasks:
          - name: Install required packages
            yum:
                    name:
                            - chrony
                            - curl
                            - unzip
                            - tar
                            - wget
                            - openssh-clients
                            - openssh
                            - gcc
                            - openssl
                            - openssl-devel
                            - bzip2-devel
                            - libffi-devel
                            - libcurl-devel
                            - postgresql-jdbc
                    state: present
          - name: Install Python2.7
            dnf:
                    name:
                            - python2-devel
                            - python2-pip
                            - python2
                    state: present
          - name: Set Postgres jar permissions
            file:
                    path: /usr/share/java/postgresql-jdbc.jar
                    mode: '0644'
          - name: Setup /etc/hosts file
            lineinfile:
                    dest: /etc/hosts
                    line: 127.0.0.1 localhost
                    state: present
                    insertafter: EOF
                    create: False
          - name: Setup network configuration file
            blockinfile:
                    dest: /etc/sysconfig/network
                    block: |
                      NETWORKING=yes
                      HOSTNAME=localhost
                    state: present
                    insertafter: EOF
          - name: Disable iptables
            service:
                    name: firewalld
                    state: stopped
                    enabled: False
          - name: Disable SELinux
            lineinfile:
                    dest: /etc/selinux/config
                    line: setenforce 0
                    state: present
                    insertafter: EOF
                    create: True
          - name: Disable PackageKit
            lineinfile:
                    dest: /etc/yum/pluginconf.d/refresh-packagekit.conf
                    line: enabled=0
                    state: present
                    insertafter: EOF
                    create: True
          - name: Set UMASK
            shell: umask 0022
          - name: Sete UMASK for all users
            lineinfile:
                    dest: /etc/profile
                    line: umask 0022
                    state: present
                    insertafter: EOF
                    create: True
